version: '3.3'

services:

  anaconda:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
       - ./notebooks:/opt/notebooks
       - ./data:/opt/project/data
    ports:
      - "8888:8888"
    command:
      /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root
    tty: true